name: Cross build and emulation of s390x using docker container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: user/app:test

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container for s390x
        uses: docker/build-push-action@v5
        with:
          platforms: linux/s390x
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Run built s390x container image
        run: |
          docker run --rm ${{ env.TEST_TAG }} 
      - name: Run other s390x container image
        run: |
          docker run --rm s390x/alpine uname -a
