name: Cross build and emulation of s390x on host

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install tools
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -q -y qemu-user qemu-user-static crossbuild-essential-s390x
    - name: Compile C program for s390x (Cross Compiling)
      run: |
        s390x-linux-gnu-gcc test.c -o test
    - name: Check and run built s390x program
      run: |
        file ./test
        qemu-s390x -L /usr/s390x-linux-gnu/ ./test
    - name: Install and run s390x version of Node.js
      run: |
        curl -O https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-s390x.tar.xz
        tar -xf node-v20.10.0-linux-s390x.tar.xz
        cd node-v20.10.0-linux-s390x/bin
        qemu-s390x -L /usr/s390x-linux-gnu/ ./node -v
