name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: s390x/alpine

    steps:
    - name: checkout
      uses: actions/checkout
    - name: Set up QEMU
      uses: ./github/actions/test-action
    - name: Test
      run: |
        uname -a
