name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Test
      run: |
        cd /proc/sys/fs/binfmt_misc
        ls -l
        cat qemu-s390x
