name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Check
      run: |
        cd /proc/sys/fs/binfmt_misc
        ls -l
        cat qemu-s390x
    - name: Test
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -q -y crossbuild-essential-s390x
        curl -O https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-s390x.tar.xz
        tar -xf node-v20.10.0-linux-s390x.tar.xz
        cd node-v20.10.0-linux-s390x/bin
        qemu-s390x -L /usr/s390x-linux-gnu/ ./node
